FROM --platform=$BUILDPLATFORM golang:1.26.8-bookworm@sha256:9fdc884aacc3bec89b20ffc69f4bb369c78210e3e4f600387b5128b12c199f81 AS build
WORKDIR /src
ENV GOTOOLCHAIN=local
COPY go.mod go.sum ./
ARG TARGETOS
ARG TARGETARCH
RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH \
    go build -mod=readonly -trimpath -buildvcs=false -ldflags='-s -w' \
      -o /out/nats-server github.com/nats-io/nats-server/v2 && \
    module_directory=$(go list -mod=readonly -m -f '{{.Dir}}' github.com/nats-io/nats-server/v2) && \
    cp "$module_directory/LICENSE" /out/nats-server.LICENSE

FROM scratch AS runtime
COPY --from=build /out/nats-server /nats-server
COPY --from=build /out/nats-server.LICENSE /licenses/nats-server.LICENSE
USER 65532:65532
STOPSIGNAL SIGTERM
ENTRYPOINT ["/nats-server"]
CMD ["--help"]

FROM runtime AS final
