ALTER TABLE uem_inventory_audit DROP CONSTRAINT uem_inventory_audit_action_check;
ALTER TABLE uem_inventory_audit ADD CONSTRAINT uem_inventory_audit_action_check
 CHECK (action IN ('inventory.desktop.read','inventory.software.read','inventory.network.read','inventory.storage.read','inventory.peripherals.read','inventory.memory.read','inventory.shares.read','inventory.security.read','inventory.devices.list','inventory.devices.export_csv','inventory.devices.export_json','inventory.groups.list','inventory.groups.read','inventory.groups.create','inventory.groups.revise','inventory.tags.list','inventory.tags.read','inventory.tags.create','inventory.tags.update','inventory.tags.delete','inventory.tags.assign','inventory.tags.unassign','inventory.profile_tags.assign','inventory.profile_tags.unassign','inventory.profiles.enable','inventory.profiles.disable','inventory.profiles.update','inventory.profiles.delete','inventory.profiles.create','inventory.profiles.clone','inventory.tasks.enable','inventory.tasks.disable','inventory.tasks.reorder','inventory.tasks.list','inventory.tasks.delete_review','inventory.tasks.delete','inventory.tasks.clone_review','inventory.tasks.clone','inventory.tasks.create_review','inventory.tasks.create','inventory.tasks.wizard_read','inventory.tasks.edit_review','inventory.tasks.update','inventory.profiles.read','inventory.profile_tags.read','inventory.profiles.move_global','inventory.profiles.move_organization'));
ALTER TABLE uem_inventory_audit DROP CONSTRAINT uem_inventory_audit_tenant_id_check;
ALTER TABLE uem_inventory_audit ADD CONSTRAINT uem_inventory_audit_tenant_id_check
 CHECK (tenant_id>0 OR (tenant_id=0 AND site_id=0 AND action IN ('inventory.profile_tags.assign','inventory.profile_tags.unassign','inventory.profiles.enable','inventory.profiles.disable','inventory.profiles.update','inventory.profiles.delete','inventory.profiles.create','inventory.profiles.clone','inventory.tasks.enable','inventory.tasks.disable','inventory.tasks.reorder','inventory.tasks.list','inventory.tasks.delete_review','inventory.tasks.delete','inventory.tasks.clone_review','inventory.tasks.clone','inventory.tasks.create_review','inventory.tasks.create','inventory.tasks.wizard_read','inventory.tasks.edit_review','inventory.tasks.update','inventory.profiles.read','inventory.profile_tags.read','inventory.profiles.move_global')));
ALTER TABLE uem_inventory_audit DROP CONSTRAINT uem_inventory_audit_site_id_check;
ALTER TABLE uem_inventory_audit ADD CONSTRAINT uem_inventory_audit_site_id_check
 CHECK (site_id>0 OR (site_id=0 AND action IN ('inventory.devices.list','inventory.devices.export_csv','inventory.devices.export_json','inventory.groups.list','inventory.groups.read','inventory.groups.create','inventory.groups.revise','inventory.tags.list','inventory.tags.read','inventory.tags.create','inventory.tags.update','inventory.tags.delete','inventory.profile_tags.assign','inventory.profile_tags.unassign','inventory.profiles.enable','inventory.profiles.disable','inventory.profiles.update','inventory.profiles.delete','inventory.profiles.create','inventory.profiles.clone','inventory.tasks.enable','inventory.tasks.disable','inventory.tasks.reorder','inventory.tasks.list','inventory.tasks.delete_review','inventory.tasks.delete','inventory.tasks.clone_review','inventory.tasks.clone','inventory.tasks.create_review','inventory.tasks.create','inventory.tasks.wizard_read','inventory.tasks.edit_review','inventory.tasks.update','inventory.profiles.read','inventory.profile_tags.read','inventory.profiles.move_global','inventory.profiles.move_organization')));
